version: "3"
services:
  batfish:
    image: "batfish/batfish"
    container_name: "batfish"
    ports:
      - "9996:9996"
      - "9997:9997"
  batfish-wrapper:
    image: "ghcr.io/ool-mddo/batfish-wrapper:main" 
    environment:
      BATFISH_HOST: batfish
    ports:
      - "5000:5000"
    depends_on:
      - batfish
